sudo: required
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    # - google-chrome-stable
    # - chromium-chromedriver
  chrome: stable
language: ruby
rvm:
  - 2.6.3
before_install:
  - gem install rake
services:
  - postgresql
  - xvfb
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - export DISPLAY=:99.0 && sleep 3
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn
script: 
  - "travis_wait 30 sleep 1800 &"
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
